// <auto-generated />
namespace Xekina.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requestlogone2many : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requestlogone2many));
        
        string IMigrationMetadata.Id
        {
            get { return "201708221527329_requestlogone2many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
